# Site settings
title: Stereo Semantics
email: your-email@domain.com
description: Description to come
baseurl: "/blahblah"
url: "http://stereosemantics.com"
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty
