# Site settings
title: Stereo Semantics
email: webmaster@stereosemantics.com
description: We put the rad in radio!
baseurl: "/blahblah"
url: "http://www.stereosemantics.com"
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

date_format: "%b %d %Y"
